"""add product_id to order_items

Revision ID: 55f2d29866e6
Revises: 9259f0b815a0
Create Date: 2026-01-31 11:43:16.294220-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f2d29866e6'
down_revision: Union[str, None] = '9259f0b815a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=True, comment='ID do produto.'))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='ID do pedido.',
               existing_comment='ID do produto (NULL se produto foi deletado).')
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'products', ['order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID do produto (NULL se produto foi deletado).',
               existing_comment='ID do pedido.')
    op.drop_column('order_items', 'product_id')
    # ### end Alembic commands ###
