"""add orders and order_items tables

Revision ID: 9259f0b815a0
Revises: 7de30c37c5ad
Create Date: 2026-01-29 14:37:19.966320-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9259f0b815a0'
down_revision: Union[str, None] = '7de30c37c5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=True, comment='ID do produto (NULL se produto foi deletado).'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='Nome do produto no momento da compra (snapshot).'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantidade comprada.'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Preço unitário pago (congelado).'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de registro.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da criação do registro.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização do registro.'),
    sa.CheckConstraint('price >= 0', name='check_non_negative_price_order'),
    sa.CheckConstraint('quantity > 0', name='check_positive_quantity_order'),
    sa.ForeignKeyConstraint(['order_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID do usuário que fez o pedido.'),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor total do pedido (congelado no momento da compra).'),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False, comment='Status atual do pedido.'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de registro.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da criação do registro.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização do registro.'),
    sa.CheckConstraint('total_price >= 0', name='check_non_negative_total'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
